name: moto_tracker
description: A motorcycle maintenance and fuel tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  intl: ^0.17.0
  fl_chart: ^0.62.0
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7
  file_picker: ^5.3.1
  permission_handler: ^10.2.0
  flutter_local_notifications: ^13.0.0
  flutter_svg: ^2.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
